# Generated by Django 3.1.5 on 2021-01-30 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Invernadero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
